#!/bin/sh

uci -q set argon.@global[0].mode='normal'
uci -q set argon.@global[0].primary='#5e72e4'
uci -q set argon.@global[0].dark_primary='#483d8b'
uci -q set argon.@global[0].transparency='0.5'
uci -q set argon.@global[0].transparency_dark='0.5'
uci -q set argon.@global[0].blur='10'
uci -q set argon.@global[0].blur_dark='10'
uci -q set argon.@global[0].online_wallpaper='none'
uci -q commit argon

exit 0