#!/bin/sh

# These defaults are packaged into every image, so they can run after sysupgrade too.
[ -f /etc/backup/installed_packages.txt ] && exit 0

firmware_repo="$(uci -q get amlogic.config.amlogic_firmware_repo)"
case "${firmware_repo}" in
    ""|https://github.com/ophub/amlogic-s9xxx-openwrt)
        uci -q set amlogic.config.amlogic_firmware_repo='https://github.com/etnperlong/amlogic-s9xxx-openwrt'
        uci -q commit amlogic
        ;;
esac

exit 0
